### ISSUE TITLE
可以使用wsl来编译码

### ISSUE THREAD

**Issue by Yo-yo-ooo** [Minep/lunaix-os#11]
wsl 是Windows Subsystem for linux

**Comment by Minep** [comment]
That's an interesting suggestion. I haven't tried it, you are welcomed to do such experiment. Theoretically, it should be fine, as the  compilation of this project only requires a proper setup of gcc (with target=i686-elf) as cross compiler and does not depend on any Linux tricks and warts. 

Let me know if you encounter any issue during your attempts.

**Comment by Minep** [comment]
I am closing this issue, feel free to reopen if you have any follow-ups.
