### ISSUE TITLE
Side-effect-free infinity-loop is undefined behaviour in C

### ISSUE THREAD

**Issue by xtexChooser** [Minep/lunaix-os#16]
[WG14/N1528](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1528.htm)
[C23 standard(WG14/N3096,ISO/IEC 9899:2023)](https://open-std.org/JTC1/SC22/WG14/www/docs/n3096.pdf)
According to ISO/IEC 9899:2023 6.8.5,
> An iteration statement may be assumed by the implementation to terminate if its controlling
expression is not a constant expression200), and none of the following operations are performed in its body, controlling expression or (in the case of a for statement) its expression-3201) :

> 201) This is intended to allow compiler transformations such as removal of empty loops even when termination cannot be proven.

simply `while (1);` can be assumed by compilers to terminate.

> 其实就是我写的时候开了O3被clang编译没了直接int3了

https://github.com/Minep/lunaix-os/blob/17fe1418db474b23d9f516db049772dfe3d8696c/lunaix-os/includes/lunaix/spike.h#L70
https://github.com/Minep/lunaix-os/blob/17fe1418db474b23d9f516db049772dfe3d8696c/lunaix-os/debug/sdbg.c#L100

**Comment by Minep** [comment]
That is the good catch, I will look into that and hopefully comes up with a decent solution. The Lunaix only tested up to -O2, with GCSE disabled. so I am sure more things like this will be spotted in the future commits. 

Nevertheless, figuring out these optimisation quirks especially under such extreme case like -O3 is a time consuming and rather tedious task for me in the current stage of development. I am truly grateful that such issue has been raised.

Anyway, well done.

**Comment by Minep** [comment]
I have take a closer look into your reporting, and have confirm that it is indeed an undefined behavior as it behaves differently in gcc with same optimization level, where the loop is able to generated. 

A possible fix would be adding noreturn attribute for a better compiler hint. The fix will be placed in the next coming merge into master, as there is a major refactoring taking place....

**Comment by xtexChooser** [comment]
Another architecture-specific way is `asm volatile("hlt");`

**Comment by xtexChooser** [comment]
for clang: `__attribute__((clang:optnone))`
