### ISSUE TITLE
如何解决版本不一致问题

### ISSUE THREAD

**Issue by rightevil** [Minep/lunaix-os#17]
就是我在看你的教程的过程中，发现一个比较大的问题，就比如你的前期写vga那段的makefile文件，因为比较长，然后你就跳过了吗，对于这种跳过的文件，我一般都是较短的话就暂停，然后照着一个一个打，但是那种较长的，比如哪个makefile文件。你的视频中当时是有56行左右，然后出现的时间也不长，我也不好暂停抄，然后想着来github复制一下，发现你的是最终版了，我复制下去运行一下就是报错，因为还有很多东西我都还没跟上来，这个只能自己把makefile给学了，然后自己手撸吗？还是说暂时跳过这个，等到了最后面的时候才执行吗？

**Comment by Minep** [comment]
非常抱歉，这的确是我当时的疏忽。关于这个问题，你可以通过commit hash来看历史文件的内容，这个hash在slides/code-map里面有列举，对应着每个话题。

至于makefile，最好也去同步地学习一下。当然了，也不是非得用makefile，如果你有自己偏好的构建工具（如cmake或者ninja），那也是可以去尝试的。

至于视频不详细讲解makefile的问题，毕竟这是一个关于OS的教程，主要注重OS的设计和实现。而C语言的使用编译一般都是默认观众已经了解，或者可以通过别的渠道学习。

希望上述回复对你有帮助！

**Comment by rightevil** [comment]
非常感谢你能抽出时间来解答我的问题，因为没怎么接触过GitHub，我虽然有看历史提交的想法，但是不知道该怎么实现，你的回答对我很有帮助，感谢大佬

**Comment by Minep** [comment]
乐意之至。如果还有什么与该话题相关的问题，欢迎重开此issue。
