### ISSUE TITLE
关于lib函数的一点疑问

### ISSUE THREAD

**Issue by Maoreus** [Minep/lunaix-os#18]
请问lib中有些函数用纯c，有些使用汇编是什么原因？
举例：
1. memcpy: asm volatile("movl %1, %%edi\n"
                 "rep movsb\n" ::"S"(src),
                 "r"(dest),
                 "c"(num)
                 : "edi", "memory");
其中rep指令的使用看得不是很明白、

2.  关于memmove为何使用u8_t的类型？

看源码的时候产生了一些困惑，期待您的解答。

**Comment by Minep** [comment]
对于第一点：内联汇编的使用主要是为了性能上的考虑。理想的情况下，我们希望为每一个这些必要且简单的功能找到指令集层面的等价（如x86提供rep指令前缀来重复执行被修饰的指令，具体的用法可以直接查Intel的x86手册），或者用汇编直接写出他的优化形式。当然，编译器也可以进行这些优化，但写成汇编可以保证一个比较consistent的体验。即哪怕在便于调试的低优化等级下，我们依然可以保证这些基础库函数是高效的，从而不会产生冗长的代码造成任何明显可见的性能差异。

对于第二点：u8_t类型就是unsigned char，也就是我们通常表示一个字节的办法。如果使用别的类型的指针，我们就需要在解引用指针时去考虑该类型的大小，以避免循环导致的越界访问。这就会导致代码变得特别的臃肿繁琐。

**Comment by Maoreus** [comment]
> 对于第一点：内联汇编的使用主要是为了性能上的考虑。理想的情况下，我们希望为每一个这些必要且简单的功能找到指令集层面的等价（如x86提供rep指令前缀来重复执行被修饰的指令，具体的用法可以直接查Intel的x86手册），或者用汇编直接写出他的优化形式。当然，编译器也可以进行这些优化，但写成汇编可以保证一个比较consistent的体验。即哪怕在便于调试的低优化等级下，我们依然可以保证这些基础库函数是高效的，从而不会产生冗长的代码造成任何明显可见的性能差异。
> 
> 对于第二点：u8_t类型就是unsigned char，也就是我们通常表示一个字节的办法。如果使用别的类型的指针，我们就需要在解引用指针时去考虑该类型的大小，以避免循环导致的越界访问。这就会导致代码变得特别的臃肿繁琐。
> 
> 希望这个回答能够帮助到你！

明白了！这样子设计确实很有道理，感谢大佬的解答。
