### ISSUE TITLE
章节6.1内存管理bug

### ISSUE THREAD

**Issue by YouHui1** [Minep/lunaix-os#20]
- 代码位置：(virtual memory) e141fd4dcd5effc2dbe59a498d7ea274b7199147
- 文件：pmm.c
- 问题函数：`pmm_mark_chunk_free` 与 `pmm_mark_chunk_occupied`
- **描述**：
    在函数中需要对位图做批处理操作，在处理最后一个页表组中使用到了以下计算：
    `(((1U << (page_count > 8 ? remainder : 0)) - 1) << (8 - remainder))`
    `page_count > 8`用于判断是否需要处理最后一个页表组，但是似乎是忽略了页偏移的情况
- **测试（以`pmm_mark_chunk_occupied`举例）**：
    ```Cpp
    int main() {
        // 假设从位置0x5开始设置6个页已占用
        pmm_mark_chunk_occupied(5, 6);
        for (int i = 0; i < 3; ++i) {
            for (int j = 7; j >= 0; --j) {
                cout << (pm_bitmap[i] >> j & 1);
            }
            cout << endl;
        }
        return 0;
    }
    ```
- **运行结果**：
    ```
    00000111
    00000000
    00000000
    ```
- 添加位移后即可正确分配，如下：
    `(((1U << (page_count + offset > 8 ? remainder : 0)) - 1) << (8 - remainder))`

    ```
    00000111
    11100000
    00000000
    ```

- 其它说明：
    - 这个bug是基于我的理解给出的，我的理解可能有误
    - 这个bug似乎在目前（内存管理章节，不涉及后续章节）影响并不大甚至是没有影响，并且我稍微看了后面章节的代码，好像pmm这个文件内部已经大变样了，因此我也不清楚后续的代码是否会出现这个问题

**Comment by Minep** [comment]
感谢反馈！你说的没错，这的确是个问题，毕竟前面的group_count和remainder的计算都是带着offset的。但这个bug似乎并没有什么对后期造成什么影响——主要是pmm采用next fit查找策略，由于Lunaix前期的memory footprint基本不高，所以也就没有什么机会去出发这个bug。后来pmm因为需要记载更多的信息，于是就摒弃了位图表示法，转而使用更简单（当然也更为离谱）的数组法——当然这是一个临时的措施，计划会在某个时候改用B-tree来作。
