### ISSUE TITLE
请问能否在 Release 里面提供已经编译完毕的二进制文件

### ISSUE THREAD

**Issue by njlyf2011** [Minep/lunaix-os#4]
这样可以省去一些因为编译 GCC 或者项目源码导致的一些问题，而且更方便非 *NIX 用户的构建。

**Comment by Minep** [comment]
完全可以，很有趣的建议！
我会在每一个主要feature实现之后，以-Og进行构建，并将产生的build目录直接打包发布到Release上，主要包含：
1. 所有未链接的对象文件
2. 连接后产生的二进制(*.bin)文件
3. 打包好的可启动ISO文件
4. 调试用的符号文件
5. objdump反汇编的输出，方便调试。

希望这些可以提供足够的帮助和支持。

**Comment by njlyf2011** [comment]
好的，谢谢
