### ISSUE TITLE
Broken link to this repo from your blog

### ISSUE THREAD

**Issue by Tony-Feng** [Minep/lunaix-os#7]
Hi Lunaixsky,

I noticed that the link to this repo from your blog is not working. On your blog [project page](https://www.lunaixsky.com/MyWorks), the link for `LunaixOS` is `https://github.com/Minep/LunaixOS`, which should be updated to `https://github.com/Minep/lunaix-os` :thinking:. Hope this could be helpful!

Thanks for your great work!

Tony

**Comment by Minep** [comment]
Good catch! Thanks for your inform. Will be updated as soon as possible.
